### ISSUE TITLE
作者作者你好, 请问当前还可以用嘛

### ISSUE THREAD

**Issue by fungaegis** [ZBIGBEAR/DamaiWang#1]
作者作者你好, 请问当前还可以用嘛
我看更新的时间在2天前

**Comment by ZBIGBEAR** [comment]
可以用的，有什么问题可以贴出来，相互学习

**Comment by PrelinaKaren** [comment]
<img width="451" alt="截屏2024-06-25 13 29 05" src="https://github.com/ZBIGBEAR/DamaiWang/assets/60833196/8a76471c-aac6-484b-9be8-9774b6b78b0e">
在自动控制的Chrome里抢票页面显示“该渠道不支持购买，建议使用大麦app查询”
是不是意味着本脚本失效了？
