### ISSUE TITLE
在自动控制的抢票页面中购买按钮显示“不支持本渠道购买”

### ISSUE THREAD

**Issue by PrelinaMontelli** [ZBIGBEAR/DamaiWang#2]
<img width="451" alt="截屏2024-06-25 13 29 05" src="https://github.com/ZBIGBEAR/DamaiWang/assets/60833196/8a76471c-aac6-484b-9be8-9774b6b78b0e">

在自动控制的Chrome里抢票页面显示“该渠道不支持购买，建议使用大麦app查询”
是不是意味着本脚本失效了？

**Comment by ZBIGBEAR** [comment]
这个抢票项目只支持手机web版，你截图显示当前这个演唱会只支持大麦app,不支持手机web。所以本项目部能对该演唱会抢票。可以找找其他项目能支持购买此演唱会的平台试试。https://github.com/Guyungy/damaihelper这个项目支持麦网，淘票票、缤玩岛等多个平台，可以参考
