### ISSUE TITLE
该渠道不可用

### ISSUE THREAD

**Issue by bigbone1** [ZBIGBEAR/DamaiWang#7]
**_提示该渠道不可用，让尝试使用手机APP购买_**

**Comment by bigbone1** [comment]
809466412963，演唱会id是这个，老薛深圳的演唱会，能帮忙看下吗

**Comment by ZBIGBEAR** [comment]
> 809466412963，演唱会id是这个，老薛深圳的演唱会，能帮忙看下吗

有些票是只能大麦网app购买，其他渠道无法购买。可以找一下其他抢票软件看看
